### ISSUE TITLE
Resume pubmode development?

### ISSUE THREAD

**Issue by jshoyer** [wash/pubmode#2]
Hi there, I'm writing this issue mainly to thank you for developing pubmode---I use it almost every day because it is by far the fastest way I have found to get full text HTML with a minimum of clicking. (Perhaps Paperpile is faster and more convenient? I haven't gotten around to trying it, because I'm a firefox user and I don't really like google docs.)

I'm really not a lisp programmer, but I periodically think about improving pubmode, and I have some questions:
1. Why do the faces/text display settings change when you switch to a pubmed results buffer (or start a new search) in a frame other than the frame you initially searched from?
2. What would be the best/simplest way to avoid closing a pubmed results buffer when inserting a citation with 'return' or 'c'? I don't really use pubmode to insert cite commands in latex, but the few times I have tried I wished that the search results buffer would persist so that I could open more papers.
3. Would there be any way to fetch XML from NCBI in the background so that emacs doesn't lock up? Is this related to emacs not being multithreaded?
4. Could one efficiently use the pubmode facilities for opening full text articles in an external browser directly from a bibtex file? (This would be slightly faster that using a DOI URL [e.g. with bibtex-url], which typically takes you to an abstract page.)
5. Tangentially related: do you know if the NCBI API consistently gets full text URIs from Highwire Press articles ending '.long', instead of the '.full' ending that most crossref tools seem to use? Is there any difference between the '.long' and '.full' URIs? (I bookmark a lot of papers, and this difference prevents me from seeing if I have bookmarked something and results in redundant bookmarks).

I hope these make sense. Thanks again.

**Comment by wash** [comment]
Feel free to fork and continue development. That's the beauty of GitHub. I'm developing Paperpile for a living now and I'm afraid I don't have time for other stuff. It's sad because I used PubMode almost 4 years for writing all my papers and I can understand how useful it is for some people out there.

**Comment by jshoyer** [comment]
OK, I'll certainly make any improvements I make public. Thanks again.
